packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  esbuild: true
  lightningcss: true
  supabase: true
  unrs-resolver: false

overrides:
  'nanoid@3': 3.3.16
  'baseline-browser-mapping': 2.11.10
  'next>postcss': 8.5.25
  'next>sharp': 0.35.3
  'vfile-matter>yaml': 2.9.0
