/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SpaceRouteImport } from './routes/_space'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as SpaceSpaceIdRouteImport } from './routes/_space.$spaceId'
import { Route as SpaceIdInviteRouteImport } from './routes/$spaceId.invite'
import { Route as SpaceSpaceIdIndexRouteImport } from './routes/_space.$spaceId.index'
import { Route as SpaceSpaceIdTransactionsRouteImport } from './routes/_space.$spaceId.transactions'
import { Route as SpaceSpaceIdMembersRouteImport } from './routes/_space.$spaceId.members'
import { Route as SpaceSpaceIdCategoriesRouteImport } from './routes/_space.$spaceId.categories'
import { Route as SpaceSpaceIdAccountsRouteImport } from './routes/_space.$spaceId.accounts'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaceRoute = SpaceRouteImport.update({
  id: '/_space',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaceSpaceIdRoute = SpaceSpaceIdRouteImport.update({
  id: '/$spaceId',
  path: '/$spaceId',
  getParentRoute: () => SpaceRoute,
} as any)
const SpaceIdInviteRoute = SpaceIdInviteRouteImport.update({
  id: '/$spaceId/invite',
  path: '/$spaceId/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaceSpaceIdIndexRoute = SpaceSpaceIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpaceSpaceIdRoute,
} as any)
const SpaceSpaceIdTransactionsRoute =
  SpaceSpaceIdTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => SpaceSpaceIdRoute,
  } as any)
const SpaceSpaceIdMembersRoute = SpaceSpaceIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => SpaceSpaceIdRoute,
} as any)
const SpaceSpaceIdCategoriesRoute = SpaceSpaceIdCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => SpaceSpaceIdRoute,
} as any)
const SpaceSpaceIdAccountsRoute = SpaceSpaceIdAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => SpaceSpaceIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/$spaceId/invite': typeof SpaceIdInviteRoute
  '/$spaceId': typeof SpaceSpaceIdRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/$spaceId/accounts': typeof SpaceSpaceIdAccountsRoute
  '/$spaceId/categories': typeof SpaceSpaceIdCategoriesRoute
  '/$spaceId/members': typeof SpaceSpaceIdMembersRoute
  '/$spaceId/transactions': typeof SpaceSpaceIdTransactionsRoute
  '/$spaceId/': typeof SpaceSpaceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/$spaceId/invite': typeof SpaceIdInviteRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/$spaceId/accounts': typeof SpaceSpaceIdAccountsRoute
  '/$spaceId/categories': typeof SpaceSpaceIdCategoriesRoute
  '/$spaceId/members': typeof SpaceSpaceIdMembersRoute
  '/$spaceId/transactions': typeof SpaceSpaceIdTransactionsRoute
  '/$spaceId': typeof SpaceSpaceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_space': typeof SpaceRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/$spaceId/invite': typeof SpaceIdInviteRoute
  '/_space/$spaceId': typeof SpaceSpaceIdRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/_space/$spaceId/accounts': typeof SpaceSpaceIdAccountsRoute
  '/_space/$spaceId/categories': typeof SpaceSpaceIdCategoriesRoute
  '/_space/$spaceId/members': typeof SpaceSpaceIdMembersRoute
  '/_space/$spaceId/transactions': typeof SpaceSpaceIdTransactionsRoute
  '/_space/$spaceId/': typeof SpaceSpaceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/$spaceId/invite'
    | '/$spaceId'
    | '/auth/callback'
    | '/$spaceId/accounts'
    | '/$spaceId/categories'
    | '/$spaceId/members'
    | '/$spaceId/transactions'
    | '/$spaceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/$spaceId/invite'
    | '/auth/callback'
    | '/$spaceId/accounts'
    | '/$spaceId/categories'
    | '/$spaceId/members'
    | '/$spaceId/transactions'
    | '/$spaceId'
  id:
    | '__root__'
    | '/'
    | '/_space'
    | '/login'
    | '/logout'
    | '/$spaceId/invite'
    | '/_space/$spaceId'
    | '/auth/callback'
    | '/_space/$spaceId/accounts'
    | '/_space/$spaceId/categories'
    | '/_space/$spaceId/members'
    | '/_space/$spaceId/transactions'
    | '/_space/$spaceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SpaceRoute: typeof SpaceRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SpaceIdInviteRoute: typeof SpaceIdInviteRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_space': {
      id: '/_space'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SpaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_space/$spaceId': {
      id: '/_space/$spaceId'
      path: '/$spaceId'
      fullPath: '/$spaceId'
      preLoaderRoute: typeof SpaceSpaceIdRouteImport
      parentRoute: typeof SpaceRoute
    }
    '/$spaceId/invite': {
      id: '/$spaceId/invite'
      path: '/$spaceId/invite'
      fullPath: '/$spaceId/invite'
      preLoaderRoute: typeof SpaceIdInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_space/$spaceId/': {
      id: '/_space/$spaceId/'
      path: '/'
      fullPath: '/$spaceId/'
      preLoaderRoute: typeof SpaceSpaceIdIndexRouteImport
      parentRoute: typeof SpaceSpaceIdRoute
    }
    '/_space/$spaceId/transactions': {
      id: '/_space/$spaceId/transactions'
      path: '/transactions'
      fullPath: '/$spaceId/transactions'
      preLoaderRoute: typeof SpaceSpaceIdTransactionsRouteImport
      parentRoute: typeof SpaceSpaceIdRoute
    }
    '/_space/$spaceId/members': {
      id: '/_space/$spaceId/members'
      path: '/members'
      fullPath: '/$spaceId/members'
      preLoaderRoute: typeof SpaceSpaceIdMembersRouteImport
      parentRoute: typeof SpaceSpaceIdRoute
    }
    '/_space/$spaceId/categories': {
      id: '/_space/$spaceId/categories'
      path: '/categories'
      fullPath: '/$spaceId/categories'
      preLoaderRoute: typeof SpaceSpaceIdCategoriesRouteImport
      parentRoute: typeof SpaceSpaceIdRoute
    }
    '/_space/$spaceId/accounts': {
      id: '/_space/$spaceId/accounts'
      path: '/accounts'
      fullPath: '/$spaceId/accounts'
      preLoaderRoute: typeof SpaceSpaceIdAccountsRouteImport
      parentRoute: typeof SpaceSpaceIdRoute
    }
  }
}

interface SpaceSpaceIdRouteChildren {
  SpaceSpaceIdAccountsRoute: typeof SpaceSpaceIdAccountsRoute
  SpaceSpaceIdCategoriesRoute: typeof SpaceSpaceIdCategoriesRoute
  SpaceSpaceIdMembersRoute: typeof SpaceSpaceIdMembersRoute
  SpaceSpaceIdTransactionsRoute: typeof SpaceSpaceIdTransactionsRoute
  SpaceSpaceIdIndexRoute: typeof SpaceSpaceIdIndexRoute
}

const SpaceSpaceIdRouteChildren: SpaceSpaceIdRouteChildren = {
  SpaceSpaceIdAccountsRoute: SpaceSpaceIdAccountsRoute,
  SpaceSpaceIdCategoriesRoute: SpaceSpaceIdCategoriesRoute,
  SpaceSpaceIdMembersRoute: SpaceSpaceIdMembersRoute,
  SpaceSpaceIdTransactionsRoute: SpaceSpaceIdTransactionsRoute,
  SpaceSpaceIdIndexRoute: SpaceSpaceIdIndexRoute,
}

const SpaceSpaceIdRouteWithChildren = SpaceSpaceIdRoute._addFileChildren(
  SpaceSpaceIdRouteChildren,
)

interface SpaceRouteChildren {
  SpaceSpaceIdRoute: typeof SpaceSpaceIdRouteWithChildren
}

const SpaceRouteChildren: SpaceRouteChildren = {
  SpaceSpaceIdRoute: SpaceSpaceIdRouteWithChildren,
}

const SpaceRouteWithChildren = SpaceRoute._addFileChildren(SpaceRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SpaceRoute: SpaceRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SpaceIdInviteRoute: SpaceIdInviteRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
