import type { Metadata } from 'next';
import localFont from 'next/font/local';

import { ILayoutProps } from '@/src/interfaces';
import { cls } from '@/src/libs/utils';

import '../styles/globals.css';

export const Pretendard = localFont({
  src: [
    {
      path: '../../public/fonts/Pretendard-Black.subset.woff2',
      weight: '900',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Pretendard-ExtraBold.subset.woff2',
      weight: '800',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Pretendard-Bold.subset.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Pretendard-SemiBold.subset.woff2',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Pretendard-Medium.subset.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Pretendard-Regular.subset.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Pretendard-Light.subset.woff2',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Pretendard-ExtraLight.subset.woff2',
      weight: '200',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Pretendard-Thin.subset.woff2',
      weight: '100',
      style: 'normal',
    },
  ],
  display: 'swap',
  preload: true,
  variable: '--pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: ILayoutProps) => {
  return (
    <html lang='ko'>
      <body className={cls(Pretendard.className, 'bg-pink-100')}>
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
