import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { ILayoutProps } from '@/src/interfaces';
import './globals.css';

export const Pretendard = localFont({
  src: '../fonts/woff2/PretendardVariable.woff2',
  display: 'swap',
  variable: '--font-pretendard',
  preload: true,
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: ILayoutProps) => {
  return (
    <html lang='ko'>
      <body className={Pretendard.className}>{children}</body>
    </html>
  );
};

export default RootLayout;
